server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_URL:localhost:5432/rest-db}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      encoding: UTF-8
  rabbitmq:
    listener:
      simple:
        auto-startup: true
        default-requeue-rejected: false
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: guest
    password: guest